### ISSUE TITLE
Add AIs

### ISSUE THREAD

**Issue by Zomis** [Zomis/flexgame-server#9]
Games should be able to provide AIs, and the creator of the game should have the possibility to add them and choose their player-settings.

Should there be some AI-options as well?

**Comment by Phrancis** [comment]
I would think some options you can set for an AI would probably be desirable, although it's a little vague as to what you have in mind... UWYA?

**Comment by Zomis** [comment]
Some AI configuration examples:
- Give priority to a certain kind of moves. Currently implemented "FixedMove" AI in TicTacToe, that only makes specific moves
- "Aggressiveness", "Defensiveness" etc.
